require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
  TargetRubyVersion: 2.5

Bundler/OrderedGems:
  Enabled: false

Layout/AlignArguments:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 40
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - "spec/**/*"

Metrics/ParameterLists:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
