version: '3.7'

services:

  postgres:
    image: 'postgres:10.6-alpine'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=ahub
      - POSTGRES_PASSWORD=ahub_password
    ports:
      - 5432:5432

volumes:
  pgdata:
