version: 2

jobs:

  build:
    parallelism: 1

    environment:
      SECRET_KEY_BASE: test_secret_key_base
      SECRET_SALT: test_secret_salt

    docker:
      - image: circleci/ruby:2.5.5-node-browsers

      - image: circleci/postgres:10.6-alpine
        environment:
          POSTGRES_USER: ahub
          POSTGRES_PASSWORD: ahub_password

    working_directory: ~/appvia-hub

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle && yarn install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Lint
      - run:
          name: lint
          command: bundle exec rubocop && yarn lint

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
