- id: gke
  name: Google Kubernetes Engine (GKE)
  description: "Provisions a fully managed GKE cluster within GCP, with monitoring and logging services, and best practices enforced."

- id: aks
  name: Azure Kubernetes Service (AKS)
  description: "Provisions a fully managed AKS cluster, with monitoring and logging services, and best practices enforced."
