- id: git_hub
  name: GitHub
  for_resource_types:
    - CodeRepo
  config_spec:
    properties:
      app_id:
        title: Your GitHub App ID
        description: "The app ID for the [GitHub App](https://developer.github.com/apps/about-apps/) you have set up."
        type: string
      app_private_key:
        title: Your GitHub App private key
        description: "A private key for the [GitHub App](https://developer.github.com/apps/about-apps/) you have set up."
        type: string
      app_installation_id:
        title: Your GitHub App installation on your org
        description: "The specific installation of your GitHub App within your GitHub organisation."
        type: string
      org:
        title: Your GitHub organisation
        description: "The organisation on GitHub to manage repos for. This should be the 'login' value as specified in https://developer.github.com/v3/orgs/."
        type: string
    required:
      - app_id
      - app_private_key
      - app_installation_id
      - org

- id: quay
  name: Quay
  for_resource_types:
    - DockerRepo
  config_spec:
    properties:
      api_access_token:
        title: Quay API access token
        description: An API token to be used to communicate with the Quay.io API. This must have enough permissions to create and manage repos. This is not shown to regular users of the hub.
        type: string
      org:
        title: Your Quay organisation
        description: The organisation on Quay to manage repos for. This will be used as the namespace for all Docker repos created.
        type: string
      global_robot_name:
        title: Global robot name
        description: "MUST be in the format: <org>+<robot_name>. This global robot token will be given access to all repos created within the org on Quay. It will be shown to users so they can access repositories."
      global_robot_token:
        title: Global robot token
        description: The value of the token for the global robot.
    required:
      - api_access_token
      - org
      - global_robot_name
      - global_robot_token

- id: kubernetes
  name: Kubernetes
  for_resource_types:
    - KubeNamespace
  config_spec:
    properties:
      cluster_name:
        title: Cluster Name
        description: A name for this cluster
        type: string
      api_url:
        title: API URL
        description: The Kubernetes API URL. This can be found using `kubectl cluster-info`.
        type: string
      ca_cert:
        title: CA Certificate
        description: MUST be base64 encoded. This is the CA bundle (pem format) used by the Kubernetes API server.
        type: string
      token:
        title: Service account token
        description: A service account token used by the hub to interact with the Kubernetes API. The service account must have `cluster-admin` level permissions in order to manage namespaces, deployments and service accounts among other things. This is not shown to regular users of the hub.
        type: string
      global_service_account_name:
        title: Global service account name
        description: "This global service account will be given access to all namespaces created within the Kube cluster. It will be shown to users so they can access these namespaces."
      global_service_account_token:
        title: Global service account token
        description: The value of the token for the global service account.
    required:
      - cluster_name
      - api_url
      - ca_cert
      - token
      - global_service_account_name
      - global_service_account_token
