- id: git_hub
  name: GitHub
  config_spec:
    properties:
      app_id:
        title: Your GitHub App ID
        description: "The app ID for the [GitHub App](https://developer.github.com/apps/about-apps/) you have set up."
        type: string
      app_private_key:
        title: Your GitHub App private key
        description: "A private key for the [GitHub App](https://developer.github.com/apps/about-apps/) you have set up."
        type: string
      app_installation_id:
        title: Your GitHub App installation on your org
        description: "The specific installation of your GitHub App within your GitHub organisation."
        type: string
      org:
        title: Your GitHub organisation
        description: "The organisation on GitHub to manage repos for. This should be the 'login' value as specified in https://developer.github.com/v3/orgs/."
        type: string
    required:
      - app_id
      - app_private_key
      - app_installation_id
      - org

- id: kubernetes
  name: Kubernetes
  config_spec:
    properties:
      cluster_name:
        title: Cluster Name
        description: A name for this cluster
        type: string
      api_url:
        title: API URL
        description: The Kubernetes API URL. This can be found using `kubectl cluster-info`
        type: string
      ca_cert:
        title: CA Certificate
        description: The CA bundle (pem format) used by the Kubernetes API server
        type: string
      token:
        title: Service account token
        description: A service account token used by the hub to interact with the Kubernetes API. The service account must have `cluster-admin` level permissions in order to manage namespaces, deployments and service accounts among other things.
        type: string
    required:
      - cluster_name
      - api_url
      - ca_cert
      - token
