- id: git_hub
  name: GitHub
  config_spec:
    properties:
      org:
        title: Organisation
        description: The organisation on GitHub to manage repos for. This should be the 'login' value as specified in https://developer.github.com/v3/orgs/
        type: string
      token:
        title: API Token
        description: The API token used by the hub to interact with GitHub. This must be a GitHub "personal access token" with the ability to manage repos and teams in the organisation specified.
        type: string
        minLength: 40
        maxLength: 40
    required:
      - org
      - token
