common: &common
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') { raise 'SECRET_KEY_BASE missing from env' } %>
  secret_salt: <%= ENV.fetch('SECRET_SALT') { raise 'SECRET_SALT missing from env' } %>

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
